In [1]:
import numpy as np

In [2]:
arr = np.arange(25)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
arr2 = np.random.randint(0,50,10)
arr2

array([21, 49, 29, 34, 31,  5, 25, 46, 27,  0])

In [6]:
arr2.max()

49

In [7]:
arr2.min()

0

In [8]:
arr2.argmax()

1

In [9]:
arr2.argmin()

9

In [10]:
arr = arr.reshape(5,5)

In [11]:
arr.shape

(5, 5)

In [12]:
arr.dtype

dtype('int32')

In [13]:
my_list = [1,2,3]
my_list = np.array(my_list)
my_list

array([1, 2, 3])

In [14]:
#numpy indexi
arr1 = np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr1[8]

8

In [16]:
arr1[1:5]

array([1, 2, 3, 4])

In [17]:
arr1[:6]

array([0, 1, 2, 3, 4, 5])

In [18]:
arr1[5:] 

array([ 5,  6,  7,  8,  9, 10])

In [19]:
arr1[0:5] = 100
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [20]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
arr_2d[0][0]

5

In [22]:
arr_2d[0]

array([ 5, 10, 15])

In [23]:
arr_2d[0,0]

5

In [25]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [26]:
 arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [27]:
arrN = np.arange(1,11)

In [30]:
bool_arr = arrN > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [31]:
arrN[bool_arr]

array([ 6,  7,  8,  9, 10])

In [32]:
#operations 

In [33]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [36]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [37]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])